task:

  name: "Setting Up, Syncing, Building and Uploading..."

  timeout_in: 10h

  container:

      image: ubuntu:20.04

      cpu: 24

      memory: 12G

  

  Build-Env-Setup_script:

       - export DEBIAN_FRONTEND=noninteractive

       - apt update

       - apt install sudo

       - df -h

       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

       - apt-get install -y tzdata

       - dpkg-reconfigure --frontend noninteractive tzdata

       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache neofetch -y

       - sudo apt install python2 -y

       - sudo ln -sf /usr/bin/python2 /usr/bin/python

       - git config --global user.name "Sushrut1101"

       - git config --global user.email "guptasushrut@gmail.com"

       - git clone https://github.com/akhilnarang/scripts.git ~/scripts

       - cd ~/scripts

       - sudo bash setup/android_build_env.sh

       - cd 
       
       - mkdir lineage19

       - cd lineage19

       - repo init -u https://github.com/LineageOS/android.git -b lineage-19.1

       - git clone https://github.com/TALUAtGitHub/gtaxl-manifests.git -b lineage-19.1 .repo/local_manifests

       - repo sync --force-sync --no-tags --no-clone-bundle -c

       - . build/envsetup.sh

       - lunch lineage_gtaxllte-userdebug

       - mka otapackage


Upload_script:

      - cd out/target/product/"$DEVICE"

      - ls -lh

      - pwd

      - chmod 777 *

      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "

      - echo " "

      - echo "============================"

      - echo "Build Uploaded!"

      - echo "Please see the link Below-  "

      - echo "----------------------------"

      - cat link.txt && echo " "

      - echo "============================"
